// Curated, categorized emoji set with bilingual (uk + en) search keywords.
// Kept in-repo (no external dataset) so the picker works offline and inside the CSP.
// Each item is [emoji, "space separated keywords"].

export interface EmojiCategory {
  key: string;
  /** i18n key for the category label. */
  label: string;
  icon: string;
  list: string[];
  keywords: Record<string, string>;
}

type Item = [string, string];

const CATS: { key: string; label: string; icon: string; items: Item[] }[] = [
  {
    key: 'smileys', label: 'emoji.catSmileys', icon: '😀', items: [
      ['😀', 'smile grin посмішка усміх'], ['😃', 'smile happy радість'], ['😄', 'smile happy сміх'],
      ['😁', 'grin beaming усмішка'], ['😆', 'laugh сміх регіт'], ['😅', 'sweat laugh піт сміх'],
      ['🤣', 'rofl рол сміх regіт'], ['😂', 'joy tears сльози сміх'], ['🙂', 'slight smile усмішка'],
      ['🙃', 'upside down догори'], ['😉', 'wink підморгування'], ['😊', 'blush рум\'янець'],
      ['😇', 'halo angel янгол німб'], ['🥰', 'love hearts закоханий серця'], ['😍', 'heart eyes закоханий'],
      ['🤩', 'star struck зірки захват'], ['😘', 'kiss поцілунок'], ['😗', 'kiss поцілунок'],
      ['😚', 'kiss поцілунок'], ['😋', 'yum смакота язик'], ['😛', 'tongue язик'],
      ['😜', 'wink tongue язик'], ['🤪', 'zany goofy дурник'], ['😝', 'tongue язик'],
      ['🤑', 'money гроші'], ['🤗', 'hug обійми'], ['🤭', 'giggle хихикання'],
      ['🤫', 'shush тихо'], ['🤔', 'thinking думає роздуми'], ['🤐', 'zipper мовчати'],
      ['🤨', 'raised eyebrow брова'], ['😐', 'neutral нейтрально'], ['😑', 'expressionless'],
      ['😶', 'no mouth без рота'], ['😏', 'smirk усмішка'], ['😒', 'unamused незадоволений'],
      ['🙄', 'eye roll очі'], ['😬', 'grimace гримаса'], ['😮‍💨', 'exhale видих'],
      ['😔', 'pensive сум'], ['😪', 'sleepy сонний'], ['🤤', 'drool слина'],
      ['😴', 'sleep сон zzz'], ['😷', 'mask маска хворий'], ['🤒', 'thermometer хворий температура'],
      ['🤕', 'bandage травма'], ['🤢', 'nausea нудота'], ['🤮', 'vomit блювота'],
      ['🤧', 'sneeze чхати'], ['🥵', 'hot спека жарко'], ['🥶', 'cold холод мороз'],
      ['🥴', 'woozy паморочиться'], ['😵', 'dizzy запаморочення'], ['🤯', 'mind blown вибух мозок'],
      ['🤠', 'cowboy ковбой'], ['🥳', 'party свято вечірка'], ['🥸', 'disguise маскування'],
      ['😎', 'cool sunglasses окуляри'], ['🤓', 'nerd ботан'], ['🧐', 'monocle монокль'],
      ['😕', 'confused розгублений'], ['😟', 'worried стурбований'], ['🙁', 'frown сум'],
      ['☹️', 'frown сум'], ['😮', 'surprise здивування'], ['😯', 'hushed'],
      ['😲', 'astonished шок'], ['😳', 'flushed сором'], ['🥺', 'pleading благання'],
      ['😦', 'frown'], ['😧', 'anguished'], ['😨', 'fearful страх'],
      ['😰', 'anxious тривога'], ['😥', 'sad сум'], ['😢', 'cry сльоза плач'],
      ['😭', 'sob плач ридання'], ['😱', 'scream крик страх'], ['😖', 'confounded'],
      ['😣', 'persevere'], ['😞', 'disappointed розчарований'], ['😓', 'downcast sweat піт'],
      ['😩', 'weary втома'], ['😫', 'tired втомлений'], ['🥱', 'yawn позіхання'],
      ['😤', 'triumph злість'], ['😡', 'angry rage злість'], ['😠', 'angry сердитий'],
      ['🤬', 'cursing лайка'], ['😈', 'devil чорт'], ['👿', 'imp чорт'],
      ['💀', 'skull череп смерть'], ['💩', 'poop какашка'], ['🤡', 'clown клоун'],
      ['👻', 'ghost привид'], ['👽', 'alien прибулець'], ['🤖', 'robot робот'],
      ['🎃', 'pumpkin гарбуз halloween'], ['😺', 'cat кіт'], ['😻', 'cat love кіт'],
      ['🙀', 'cat scared кіт'], ['😹', 'cat joy кіт'],
    ],
  },
  {
    key: 'people', label: 'emoji.catPeople', icon: '🧑', items: [
      ['👋', 'wave привіт рука'], ['🤚', 'hand рука'], ['✋', 'hand долоня'], ['🖐️', 'hand долоня'],
      ['👌', 'ok окей'], ['🤌', 'pinched'], ['✌️', 'victory peace мир'], ['🤞', 'fingers crossed удача'],
      ['🤟', 'love love'], ['🤘', 'rock рок'], ['🤙', 'call дзвони'], ['👈', 'left ліворуч'],
      ['👉', 'right праворуч'], ['👆', 'up вгору'], ['👇', 'down вниз'], ['☝️', 'up'],
      ['👍', 'thumbs up лайк добре'], ['👎', 'thumbs down дизлайк'], ['✊', 'fist кулак'],
      ['👊', 'punch кулак'], ['👏', 'clap оплески'], ['🙌', 'raise hands ура'],
      ['👐', 'open hands'], ['🤲', 'palms'], ['🤝', 'handshake рукостискання угода'],
      ['🙏', 'pray дякую молитва'], ['✍️', 'writing пишу'], ['💅', 'nails манікюр'],
      ['💪', 'muscle сила'], ['🦵', 'leg нога'], ['🦶', 'foot ступня'], ['👂', 'ear вухо'],
      ['👃', 'nose ніс'], ['🧠', 'brain мозок'], ['🦷', 'tooth зуб'], ['👀', 'eyes очі'],
      ['👁️', 'eye око'], ['👅', 'tongue язик'], ['👄', 'lips губи'], ['👶', 'baby немовля'],
      ['🧒', 'child дитина'], ['👦', 'boy хлопчик'], ['👧', 'girl дівчинка'], ['🧑', 'person людина'],
      ['👨', 'man чоловік'], ['👩', 'woman жінка'], ['🧔', 'beard борода'], ['👴', 'old man дід'],
      ['👵', 'old woman баба'], ['🧓', 'older older'], ['👮', 'police поліція'], ['🕵️', 'detective детектив'],
      ['💂', 'guard'], ['👷', 'worker будівельник'], ['🤴', 'prince принц'], ['👸', 'princess принцеса'],
      ['👳', 'turban'], ['🧕', 'hijab'], ['🤵', 'tuxedo'], ['👰', 'bride наречена'],
      ['🤰', 'pregnant вагітна'], ['🍼', 'bottle пляшечка'], ['👼', 'angel янгол'],
      ['🎅', 'santa дід мороз'], ['🤶', 'mrs claus'], ['🦸', 'superhero супергерой'], ['🦹', 'villain лиходій'],
      ['🧙', 'wizard чарівник'], ['🧚', 'fairy фея'], ['🧛', 'vampire вампір'], ['🧜', 'mermaid русалка'],
      ['🧝', 'elf ельф'], ['🧞', 'genie джин'], ['🧟', 'zombie зомбі'], ['💆', 'massage масаж'],
      ['💇', 'haircut стрижка'], ['🚶', 'walk йде'], ['🏃', 'run біг'], ['💃', 'dance танець'],
      ['🕺', 'dance танець'], ['👯', 'dancers'], ['🧗', 'climb скеле'], ['🏇', 'horse racing'],
      ['🏄', 'surf серф'], ['🚣', 'row човен'], ['🏊', 'swim плавання'], ['🚴', 'cycling велосипед'],
      ['🤸', 'cartwheel'], ['🤼', 'wrestle'], ['🤽', 'water polo'], ['🤾', 'handball'],
      ['🧘', 'yoga йога'], ['🛀', 'bath ванна'], ['👪', 'family сім\'я родина'], ['👫', 'couple пара'],
    ],
  },
  {
    key: 'animals', label: 'emoji.catAnimals', icon: '🐶', items: [
      ['🐶', 'dog собака пес'], ['🐱', 'cat кіт кішка'], ['🐭', 'mouse миша'], ['🐹', 'hamster хом\'як'],
      ['🐰', 'rabbit кролик заєць'], ['🦊', 'fox лисиця'], ['🐻', 'bear ведмідь'], ['🐼', 'panda панда'],
      ['🐨', 'koala коала'], ['🐯', 'tiger тигр'], ['🦁', 'lion лев'], ['🐮', 'cow корова'],
      ['🐷', 'pig свиня'], ['🐸', 'frog жаба'], ['🐵', 'monkey мавпа'], ['🙈', 'monkey мавпа'],
      ['🐔', 'chicken курка'], ['🐧', 'penguin пінгвін'], ['🐦', 'bird пташка'], ['🐤', 'chick курча'],
      ['🦆', 'duck качка'], ['🦅', 'eagle орел'], ['🦉', 'owl сова'], ['🦇', 'bat кажан'],
      ['🐺', 'wolf вовк'], ['🐗', 'boar кабан'], ['🐴', 'horse кінь'], ['🦄', 'unicorn єдиноріг'],
      ['🐝', 'bee бджола'], ['🐛', 'bug гусениця'], ['🦋', 'butterfly метелик'], ['🐌', 'snail равлик'],
      ['🐞', 'ladybug сонечко'], ['🐜', 'ant мураха'], ['🦗', 'cricket'], ['🕷️', 'spider павук'],
      ['🦂', 'scorpion скорпіон'], ['🐢', 'turtle черепаха'], ['🐍', 'snake змія'], ['🦎', 'lizard ящірка'],
      ['🦖', 'dino динозавр'], ['🐙', 'octopus восьминіг'], ['🦑', 'squid кальмар'], ['🦐', 'shrimp креветка'],
      ['🦀', 'crab краб'], ['🐡', 'fish риба'], ['🐠', 'fish риба'], ['🐟', 'fish риба'],
      ['🐬', 'dolphin дельфін'], ['🐳', 'whale кит'], ['🐋', 'whale кит'], ['🦈', 'shark акула'],
      ['🐊', 'crocodile крокодил'], ['🐅', 'tiger тигр'], ['🐆', 'leopard'], ['🦓', 'zebra зебра'],
      ['🦍', 'gorilla горила'], ['🐘', 'elephant слон'], ['🦏', 'rhino носоріг'], ['🐪', 'camel верблюд'],
      ['🦒', 'giraffe жираф'], ['🐐', 'goat коза'], ['🐑', 'sheep вівця'], ['🐕', 'dog собака'],
      ['🐈', 'cat кіт'], ['🐓', 'rooster півень'], ['🦃', 'turkey індик'], ['🦚', 'peacock павич'],
      ['🦜', 'parrot папуга'], ['🦢', 'swan лебідь'], ['🐇', 'rabbit кролик'], ['🐿️', 'squirrel білка'],
      ['🦔', 'hedgehog їжак'], ['🌵', 'cactus кактус'], ['🌲', 'tree ялинка дерево'], ['🌳', 'tree дерево'],
      ['🌴', 'palm пальма'], ['🌱', 'seedling паросток'], ['🌿', 'herb трава'], ['☘️', 'clover конюшина'],
      ['🍀', 'clover конюшина удача'], ['🍁', 'maple листок'], ['🍂', 'leaves листя'], ['🍄', 'mushroom гриб'],
      ['🌷', 'tulip тюльпан'], ['🌹', 'rose троянда'], ['🌻', 'sunflower соняшник'], ['🌼', 'flower квітка'],
      ['🌸', 'blossom квітка'], ['💐', 'bouquet букет'],
    ],
  },
  {
    key: 'food', label: 'emoji.catFood', icon: '🍔', items: [
      ['🍏', 'apple яблуко'], ['🍎', 'apple яблуко'], ['🍐', 'pear груша'], ['🍊', 'orange апельсин'],
      ['🍋', 'lemon лимон'], ['🍌', 'banana банан'], ['🍉', 'watermelon кавун'], ['🍇', 'grapes виноград'],
      ['🍓', 'strawberry полуниця'], ['🫐', 'blueberry чорниця'], ['🍒', 'cherry вишня'], ['🍑', 'peach персик'],
      ['🥭', 'mango манго'], ['🍍', 'pineapple ананас'], ['🥥', 'coconut кокос'], ['🥝', 'kiwi ківі'],
      ['🍅', 'tomato помідор'], ['🍆', 'eggplant баклажан'], ['🥑', 'avocado авокадо'], ['🥦', 'broccoli броколі'],
      ['🥬', 'lettuce салат'], ['🥒', 'cucumber огірок'], ['🌶️', 'pepper перець'], ['🌽', 'corn кукурудза'],
      ['🥕', 'carrot морква'], ['🧄', 'garlic часник'], ['🧅', 'onion цибуля'], ['🥔', 'potato картопля'],
      ['🍠', 'sweet potato'], ['🥐', 'croissant круасан'], ['🥯', 'bagel бейгл'], ['🍞', 'bread хліб'],
      ['🥖', 'baguette багет'], ['🧀', 'cheese сир'], ['🥚', 'egg яйце'], ['🍳', 'fried egg яєчня'],
      ['🥞', 'pancakes млинці'], ['🧇', 'waffle вафля'], ['🥓', 'bacon бекон'], ['🥩', 'steak м\'ясо стейк'],
      ['🍗', 'chicken курка'], ['🍖', 'meat м\'ясо'], ['🌭', 'hotdog хотдог'], ['🍔', 'burger бургер'],
      ['🍟', 'fries картопля фрі'], ['🍕', 'pizza піца'], ['🥪', 'sandwich сендвіч'], ['🌮', 'taco тако'],
      ['🌯', 'burrito буріто'], ['🥙', 'pita піта'], ['🧆', 'falafel'], ['🥗', 'salad салат'],
      ['🍝', 'pasta паста'], ['🍜', 'ramen локшина'], ['🍲', 'stew суп'], ['🍛', 'curry'],
      ['🍣', 'sushi суші'], ['🍱', 'bento'], ['🥟', 'dumpling вареник пельмень'], ['🦪', 'oyster устриця'],
      ['🍤', 'shrimp креветка'], ['🍙', 'rice ball'], ['🍚', 'rice рис'], ['🍘', 'rice'],
      ['🍥', 'fish cake'], ['🥮', 'mooncake'], ['🍢', 'oden'], ['🍡', 'dango'],
      ['🍦', 'ice cream морозиво'], ['🍨', 'ice cream морозиво'], ['🍧', 'shaved ice'], ['🥧', 'pie пиріг'],
      ['🧁', 'cupcake кекс'], ['🍰', 'cake торт'], ['🎂', 'birthday cake торт'], ['🍮', 'pudding'],
      ['🍭', 'lollipop льодяник'], ['🍬', 'candy цукерка'], ['🍫', 'chocolate шоколад'], ['🍿', 'popcorn попкорн'],
      ['🍩', 'donut пончик'], ['🍪', 'cookie печиво'], ['🌰', 'chestnut'], ['🥜', 'peanut горіх'],
      ['🍯', 'honey мед'], ['🥛', 'milk молоко'], ['☕', 'coffee кава'], ['🍵', 'tea чай'],
      ['🧃', 'juice сік'], ['🥤', 'soda напій'], ['🧋', 'bubble tea'], ['🍺', 'beer пиво'],
      ['🍻', 'beers пиво'], ['🥂', 'cheers шампанське'], ['🍷', 'wine вино'], ['🥃', 'whisky віскі'],
      ['🍸', 'cocktail коктейль'], ['🍹', 'tropical'], ['🍾', 'champagne шампанське'], ['🧉', 'mate'],
    ],
  },
  {
    key: 'travel', label: 'emoji.catTravel', icon: '✈️', items: [
      ['🚗', 'car авто машина'], ['🚕', 'taxi таксі'], ['🚙', 'suv авто'], ['🚌', 'bus автобус'],
      ['🚎', 'trolley тролейбус'], ['🏎️', 'race car'], ['🚓', 'police car'], ['🚑', 'ambulance швидка'],
      ['🚒', 'fire truck'], ['🚐', 'van'], ['🚚', 'truck вантажівка'], ['🚛', 'truck фура'],
      ['🚜', 'tractor трактор'], ['🛵', 'scooter скутер'], ['🏍️', 'motorcycle мотоцикл'], ['🚲', 'bike велосипед'],
      ['🛴', 'kick scooter самокат'], ['🚨', 'siren сирена'], ['🚔', 'police'], ['🚍', 'bus'],
      ['🚄', 'train потяг'], ['🚅', 'train швидкісний'], ['🚈', 'train'], ['🚂', 'locomotive паровоз'],
      ['🚆', 'train'], ['🚇', 'metro метро'], ['🚊', 'tram трамвай'], ['🚝', 'monorail'],
      ['🚉', 'station станція'], ['✈️', 'plane літак'], ['🛫', 'takeoff зліт'], ['🛬', 'landing посадка'],
      ['🛩️', 'small plane'], ['💺', 'seat крісло'], ['🚁', 'helicopter вертоліт'], ['🚀', 'rocket ракета'],
      ['🛸', 'ufo нло'], ['🚢', 'ship корабель'], ['⛴️', 'ferry пором'], ['🛥️', 'boat катер'],
      ['🚤', 'speedboat'], ['⛵', 'sailboat вітрильник'], ['🛶', 'canoe каное'], ['⚓', 'anchor якір'],
      ['⛽', 'fuel заправка бензин'], ['🚧', 'construction'], ['🚦', 'traffic light світлофор'], ['🗺️', 'map мапа'],
      ['🧭', 'compass компас'], ['🏔️', 'mountain гора'], ['⛰️', 'mountain гора'], ['🌋', 'volcano вулкан'],
      ['🏕️', 'camping намет'], ['🏖️', 'beach пляж'], ['🏝️', 'island острів'], ['🏜️', 'desert пустеля'],
      ['🏛️', 'building будівля'], ['🏗️', 'crane будівництво'], ['🏠', 'house дім будинок'], ['🏡', 'home дім'],
      ['🏢', 'office офіс'], ['🏬', 'store магазин'], ['🏣', 'post'], ['🏥', 'hospital лікарня'],
      ['🏦', 'bank банк'], ['🏨', 'hotel готель'], ['🏪', 'store магазин'], ['🏫', 'school школа'],
      ['🏩', 'love hotel'], ['💒', 'wedding весілля'], ['⛪', 'church церква'], ['🕌', 'mosque мечеть'],
      ['🛕', 'temple храм'], ['🕍', 'synagogue'], ['🏯', 'castle замок'], ['🏰', 'castle замок'],
      ['🗼', 'tower вежа'], ['🗽', 'liberty статуя'], ['🌁', 'foggy'], ['🌉', 'bridge міст'],
      ['🎡', 'ferris wheel'], ['🎢', 'roller coaster'], ['🎠', 'carousel'], ['⛲', 'fountain фонтан'],
      ['🏙️', 'city місто'], ['🌃', 'night ніч'], ['🌆', 'sunset захід'], ['🌇', 'sunset'],
    ],
  },
  {
    key: 'activities', label: 'emoji.catActivities', icon: '⚽', items: [
      ['⚽', 'soccer футбол м\'яч'], ['🏀', 'basketball баскетбол'], ['🏈', 'football'], ['⚾', 'baseball'],
      ['🥎', 'softball'], ['🎾', 'tennis теніс'], ['🏐', 'volleyball волейбол'], ['🏉', 'rugby регбі'],
      ['🥏', 'frisbee'], ['🎱', 'billiards більярд'], ['🪀', 'yoyo'], ['🏓', 'ping pong'],
      ['🏸', 'badminton бадмінтон'], ['🥅', 'goal ворота'], ['🏒', 'hockey хокей'], ['🏑', 'field hockey'],
      ['🥍', 'lacrosse'], ['🏏', 'cricket'], ['⛳', 'golf гольф'], ['🪁', 'kite повітряний змій'],
      ['🏹', 'archery лук'], ['🎣', 'fishing риболовля'], ['🤿', 'diving'], ['🥊', 'boxing бокс'],
      ['🥋', 'martial arts'], ['🎽', 'running shirt'], ['🛹', 'skateboard скейт'], ['🛷', 'sled санки'],
      ['⛸️', 'skate ковзани'], ['🥌', 'curling'], ['🎿', 'ski лижі'], ['⛷️', 'skier лижник'],
      ['🏂', 'snowboard'], ['🏋️', 'weightlifting гиря'], ['🤺', 'fencing фехтування'], ['🤾', 'handball гандбол'],
      ['🏆', 'trophy кубок'], ['🥇', 'gold медаль'], ['🥈', 'silver медаль'], ['🥉', 'bronze медаль'],
      ['🏅', 'medal медаль'], ['🎖️', 'medal'], ['🎗️', 'ribbon'], ['🎫', 'ticket квиток'],
      ['🎟️', 'tickets'], ['🎪', 'circus цирк'], ['🤹', 'juggling'], ['🎭', 'theater театр'],
      ['🎨', 'art мистецтво палітра'], ['🎬', 'movie кіно'], ['🎤', 'mic мікрофон'], ['🎧', 'headphones навушники'],
      ['🎼', 'music ноти'], ['🎹', 'piano піаніно'], ['🥁', 'drum барабан'], ['🎷', 'sax саксофон'],
      ['🎺', 'trumpet труба'], ['🎸', 'guitar гітара'], ['🪕', 'banjo'], ['🎻', 'violin скрипка'],
      ['🎲', 'dice кубик'], ['♟️', 'chess шахи'], ['🎯', 'dart дартс ціль'], ['🎳', 'bowling боулінг'],
      ['🎮', 'game гра джойстик'], ['🎰', 'slot казино'], ['🧩', 'puzzle пазл'], ['🎨', 'palette'],
    ],
  },
  {
    key: 'objects', label: 'emoji.catObjects', icon: '💡', items: [
      ['⌚', 'watch годинник'], ['📱', 'phone телефон'], ['💻', 'laptop ноутбук'], ['⌨️', 'keyboard клавіатура'],
      ['🖥️', 'desktop комп\'ютер'], ['🖨️', 'printer принтер'], ['🖱️', 'mouse миша'], ['💽', 'disk'],
      ['💾', 'floppy save'], ['💿', 'cd'], ['📀', 'dvd'], ['📷', 'camera камера фото'],
      ['📸', 'camera фото'], ['📹', 'video камера'], ['🎥', 'movie camera'], ['📞', 'phone телефон'],
      ['☎️', 'telephone телефон'], ['📟', 'pager'], ['📠', 'fax'], ['📺', 'tv телевізор'],
      ['📻', 'radio радіо'], ['🎙️', 'mic мікрофон'], ['⏱️', 'stopwatch секундомір'], ['⏰', 'alarm будильник'],
      ['🕰️', 'clock годинник'], ['⏳', 'hourglass пісочний'], ['⌛', 'hourglass'], ['📡', 'satellite антена'],
      ['🔋', 'battery батарея'], ['🔌', 'plug розетка'], ['💡', 'bulb лампочка ідея'], ['🔦', 'flashlight ліхтарик'],
      ['🕯️', 'candle свічка'], ['🧯', 'extinguisher'], ['🛢️', 'oil'], ['💸', 'money гроші'],
      ['💵', 'dollar гроші'], ['💴', 'yen'], ['💶', 'euro євро'], ['💷', 'pound'],
      ['💰', 'money bag гроші мішок'], ['💳', 'card картка'], ['🧾', 'receipt чек рахунок'], ['💎', 'gem діамант'],
      ['⚖️', 'scale ваги'], ['🧰', 'toolbox'], ['🔧', 'wrench ключ'], ['🔨', 'hammer молоток'],
      ['⚒️', 'tools'], ['🛠️', 'tools інструменти'], ['⛏️', 'pick'], ['🔩', 'nut bolt'],
      ['⚙️', 'gear шестерня'], ['🧱', 'brick цегла'], ['⛓️', 'chain ланцюг'], ['🧲', 'magnet магніт'],
      ['🔫', 'gun пістолет'], ['💣', 'bomb бомба'], ['🧨', 'firecracker'], ['🔪', 'knife ніж'],
      ['🗡️', 'dagger'], ['🛡️', 'shield щит'], ['🚬', 'cigarette'], ['⚰️', 'coffin труна'],
      ['🏺', 'amphora'], ['🔮', 'crystal ball'], ['📿', 'beads'], ['🧿', 'nazar'],
      ['💈', 'barber'], ['🔭', 'telescope телескоп'], ['🔬', 'microscope мікроскоп'], ['🩺', 'stethoscope'],
      ['💊', 'pill таблетка'], ['💉', 'syringe шприц'], ['🩹', 'bandage пластир'], ['🌡️', 'thermometer'],
      ['🧬', 'dna днк'], ['🦠', 'microbe вірус'], ['🧪', 'test tube пробірка'], ['🧫', 'petri'],
      ['🧴', 'lotion'], ['🧼', 'soap мило'], ['🧽', 'sponge губка'], ['🧹', 'broom мітла'],
      ['🧺', 'basket кошик'], ['🧻', 'toilet paper'], ['🚽', 'toilet туалет'], ['🚿', 'shower душ'],
      ['🛁', 'bathtub ванна'], ['🔑', 'key ключ'], ['🗝️', 'key ключ'], ['🚪', 'door двері'],
      ['🛋️', 'couch диван'], ['🛏️', 'bed ліжко'], ['🖼️', 'picture картина'], ['🎁', 'gift подарунок'],
      ['🎈', 'balloon кулька'], ['🎉', 'party свято'], ['🎊', 'confetti'], ['🎀', 'ribbon бант'],
      ['✏️', 'pencil олівець'], ['✒️', 'pen ручка'], ['🖊️', 'pen ручка'], ['📝', 'memo нотатка'],
      ['📖', 'book книга'], ['📚', 'books книги'], ['📕', 'book книга'], ['📓', 'notebook зошит'],
      ['📅', 'calendar календар'], ['📆', 'calendar'], ['📌', 'pin шпилька'], ['📎', 'clip скріпка'],
      ['✂️', 'scissors ножиці'], ['📁', 'folder тека'], ['📂', 'folder'], ['🗂️', 'dividers'],
      ['📊', 'chart графік'], ['📈', 'chart up графік'], ['📉', 'chart down'], ['🗃️', 'box'],
      ['📦', 'package посилка коробка'], ['✉️', 'envelope лист'], ['📧', 'email пошта'], ['📮', 'postbox'],
    ],
  },
  {
    key: 'symbols', label: 'emoji.catSymbols', icon: '❤️', items: [
      ['❤️', 'heart red серце любов'], ['🧡', 'orange heart серце'], ['💛', 'yellow heart серце'],
      ['💚', 'green heart серце'], ['💙', 'blue heart серце'], ['💜', 'purple heart серце'],
      ['🖤', 'black heart серце'], ['🤍', 'white heart серце'], ['🤎', 'brown heart серце'],
      ['💔', 'broken heart розбите серце'], ['❣️', 'heart серце'], ['💕', 'hearts серця'],
      ['💞', 'hearts серця'], ['💓', 'heart серце'], ['💗', 'heart серце'], ['💖', 'heart серце'],
      ['💘', 'heart arrow'], ['💝', 'heart gift'], ['💟', 'heart'], ['❤️‍🔥', 'heart fire'],
      ['💯', '100 сто'], ['💢', 'anger'], ['💥', 'boom вибух'], ['💫', 'dizzy'],
      ['💦', 'sweat краплі'], ['💨', 'dash'], ['🕳️', 'hole'], ['💬', 'speech'],
      ['💭', 'thought думка'], ['💤', 'zzz сон'], ['⭐', 'star зірка'], ['🌟', 'star зірка'],
      ['✨', 'sparkles блиск'], ['⚡', 'lightning блискавка'], ['🔥', 'fire вогонь'], ['🌈', 'rainbow веселка'],
      ['☀️', 'sun сонце'], ['⛅', 'cloud sun'], ['☁️', 'cloud хмара'], ['🌧️', 'rain дощ'],
      ['⛈️', 'storm гроза'], ['❄️', 'snowflake сніжинка'], ['☃️', 'snowman сніговик'], ['💧', 'droplet крапля'],
      ['🌊', 'wave хвиля'], ['🌙', 'moon місяць'], ['🌛', 'moon'], ['🌝', 'full moon'],
      ['✅', 'check галочка ok'], ['✔️', 'check галочка'], ['❌', 'cross хрест ні'], ['❎', 'cross'],
      ['➕', 'plus плюс'], ['➖', 'minus мінус'], ['➗', 'divide'], ['✖️', 'multiply'],
      ['❓', 'question питання'], ['❗', 'exclamation'], ['⁉️', 'interrobang'], ['‼️', 'bang'],
      ['⚠️', 'warning увага'], ['🚫', 'no prohibited заборона'], ['✋', 'stop'], ['🔞', '18 no'],
      ['💲', 'dollar долар'], ['💱', 'exchange обмін'], ['♻️', 'recycle переробка'], ['⚜️', 'fleur'],
      ['🔱', 'trident'], ['📛', 'name badge'], ['🔰', 'beginner'], ['⭕', 'circle коло'],
      ['✳️', 'asterisk'], ['✴️', 'star'], ['❇️', 'sparkle'], ['©️', 'copyright'],
      ['®️', 'registered'], ['™️', 'trademark'], ['🔟', '10'], ['🔢', 'numbers'],
      ['#️⃣', 'hash'], ['*️⃣', 'star'], ['▶️', 'play'], ['⏸️', 'pause'],
      ['⏯️', 'play pause'], ['⏹️', 'stop'], ['⏭️', 'next'], ['🔀', 'shuffle'],
      ['🔁', 'repeat повтор'], ['🔂', 'repeat one'], ['🔄', 'refresh оновити'], ['🔊', 'loud звук'],
      ['🔇', 'mute'], ['🔔', 'bell дзвінок'], ['🔕', 'no bell'], ['📢', 'megaphone'],
      ['➡️', 'right'], ['⬅️', 'left'], ['⬆️', 'up'], ['⬇️', 'down'],
      ['↗️', 'up right'], ['🔝', 'top'], ['🔙', 'back'], ['🔜', 'soon'],
      ['💠', 'diamond'], ['🔷', 'blue diamond'], ['🔶', 'orange diamond'], ['🔴', 'red circle червоний'],
      ['🟠', 'orange circle'], ['🟡', 'yellow circle'], ['🟢', 'green circle зелений'], ['🔵', 'blue circle синій'],
      ['🟣', 'purple circle'], ['⚫', 'black circle'], ['⚪', 'white circle'], ['🟥', 'red square'],
      ['🟩', 'green square'], ['🟦', 'blue square'], ['⬛', 'black square'], ['⬜', 'white square'],
      ['🏁', 'checkered finish фініш'], ['🚩', 'flag прапор'], ['🏳️', 'white flag'], ['🏴', 'black flag'],
      ['🏴‍☠️', 'pirate пірат'], ['🏳️‍🌈', 'rainbow flag'], ['🇺🇦', 'ukraine україна прапор'], ['❤️‍🩹', 'mending heart'],
    ],
  },
];

export const EMOJI_CATEGORIES: EmojiCategory[] = CATS.map(cat => ({
  key: cat.key,
  label: cat.label,
  icon: cat.icon,
  list: cat.items.map(i => i[0]),
  keywords: Object.fromEntries(cat.items.map(i => [i[0], i[1].toLowerCase()])),
}));
